version: '3'
networks:
 dev_planestic:

services:
  ud-hosting-client:
     build: .
     container_name: ud-hosting-client
     restart: on-failure
     env_file:
        - .env
     networks:
        - dev_planestic
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ud-hosting-client.rule=Host(`desarrollo.planestic.udistrital.edu.co`)"
      - "traefik.http.routers.ud-hosting-client.tls=true"
      - "traefik.http.routers.ud-hosting-client.tls.certresolver=le"
      - "traefik.http.services.ud-hosting-client.loadbalancer.server.port=80"           
networks:
  dev_planestic:
    external: true
